<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchActions, fetchSignals, sendUserMessage, type ActionHistoryEntry, type SignalHistoryEntry } from '$lib/echo-client';
  export let apiBase:string; export let eventRevision=0; export let connected=false;
  let messages:SignalHistoryEntry[]=[];let actions:ActionHistoryEntry[]=[];let text='';let sending=false;let error='';let mounted=false;let seen=-1;
  $: ordered=[...messages].reverse();
  $: if(mounted&&eventRevision!==seen){seen=eventRevision;void load()}
  onMount(()=>{mounted=true;void load()});
  async function load(){try{[messages,actions]=await Promise.all([fetchSignals(window.fetch.bind(window),apiBase,{type:'UserMessage',limit:100}),fetchActions(window.fetch.bind(window),apiBase,{limit:200})]);error=''}catch{error='Chat activity is unavailable while Echo is disconnected.'}}
  async function send(){const value=text.trim();if(!value||sending)return;sending=true;error='';try{const signal=await sendUserMessage(window.fetch.bind(window),value,apiBase);text='';messages=[signal,...messages.filter((item)=>item.id!==signal.id)];await load()}catch(cause){error=cause instanceof Error?cause.message:'Message delivery failed.'}finally{sending=false}}
  function related(signalId:string){return actions.filter((action)=>action.signal_id===signalId)}
  function response(action:ActionHistoryEntry):string{for(const candidate of [action.parameters.text,action.parameters.message,action.parameters.content,action.result]){if(typeof candidate==='string')return candidate}return JSON.stringify(action.parameters)}
  function keydown(event:KeyboardEvent){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send()}}
  const time=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
</script>
<section class="chat" aria-labelledby="chat-heading"><header><div><p>Signal-routed conversation</p><h2 id="chat-heading">Chat</h2></div><span class:online={connected}>{connected?'Runtime connected':'Runtime offline · showing history'}</span></header>
  <div class="route-note"><strong>UserMessage</strong><span>Messages enter Echo as Signals. Only normal routed Tasks and Actions appear as responses.</span></div>
  <div class="conversation" aria-live="polite">{#if ordered.length}{#each ordered as message}<article class="turn"><div class="message user"><div><strong>You</strong><time datetime={message.timestamp}>{time(message.timestamp)}</time></div><p>{String(message.payload.text??'')}</p><code>{message.id}</code></div>{#if related(message.id).length}{#each related(message.id) as action}<div class="message echo"><div><strong>Echo · {action.type}</strong><span>{action.status}</span></div><p>{response(action)}</p><code>Action {action.id}</code></div>{/each}{:else}<div class="waiting">{message.routing_result.status==='unhandled'?'No handler accepted this UserMessage.':'Waiting for routed runtime activity…'}</div>{/if}</article>{/each}{:else}<div class="empty"><strong>No conversation yet</strong><span>Send a message to inject the first UserMessage Signal.</span></div>{/if}</div>
  {#if error}<div class="error" role="status">{error}</div>{/if}
  <form onsubmit={(event)=>{event.preventDefault();void send()}}><label for="message">Message Echo</label><textarea id="message" bind:value={text} onkeydown={keydown} placeholder="Type a message…" rows="3" disabled={!connected||sending}></textarea><button type="submit" disabled={!connected||sending||!text.trim()}>{sending?'Routing…':'Send as Signal'}</button></form>
</section>
<style>
  .chat{display:grid;grid-template-rows:auto auto minmax(18rem,1fr) auto;width:min(100%,62rem);height:calc(100vh - 12rem);min-height:38rem;margin:0 auto}header,.route-note,.message>div{display:flex;align-items:center;justify-content:space-between;gap:1rem}header{margin-bottom:1rem}h2,p{margin:0}h2{font-size:clamp(1.75rem,3vw,2.5rem)}header p{color:#6f8093;font:.75rem ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase;margin-bottom:.4rem}header>span{color:#ef7b84;font-size:.8rem}header>span.online{color:#58d68d}.route-note{justify-content:flex-start;padding:.75rem 1rem;border:1px solid #25404d;border-radius:.5rem .5rem 0 0;background:#0e1b24}.route-note strong{color:#57d7ce;font:.78rem ui-monospace,monospace}.route-note span{color:#8291a3;font-size:.8rem}.conversation{overflow:auto;padding:1.2rem;border:1px solid #1d2a38;border-top:0;background:#0b1119}.turn{display:grid;gap:.55rem;margin-bottom:1.2rem}.message{width:min(78%,38rem);padding:.85rem 1rem;border:1px solid #283747;border-radius:.5rem;background:#111a25}.message.user{justify-self:end;border-color:#245258;background:#10242a}.message.echo{justify-self:start}.message strong{font-size:.78rem}.message time,.message span,.message code{color:#718196;font:.68rem ui-monospace,monospace}.message p{margin:.55rem 0;color:#d7e1ea;line-height:1.5;white-space:pre-wrap}.waiting{justify-self:start;padding:.45rem .7rem;color:#728195;font-size:.75rem}.empty{display:grid;place-content:center;gap:.5rem;height:100%;text-align:center;color:#657487}.empty strong{color:#9aa8b8}.error{padding:.7rem 1rem;border:1px solid #5d3038;color:#efb1b6;background:#251218}form{position:relative;display:grid;grid-template-columns:1fr auto;gap:.6rem;padding:1rem;border:1px solid #1d2a38;border-top:0;border-radius:0 0 .5rem .5rem;background:#101821}form label{position:absolute;width:1px;height:1px;overflow:hidden}textarea{resize:none;min-width:0;padding:.75rem;border:1px solid #314153;border-radius:.4rem;color:#e1e9f1;background:#0a1119;font:1rem/1.4 inherit}textarea:focus{border-color:#4ccbc5;outline:none}button{align-self:end;padding:.7rem 1rem;border:1px solid #28736f;border-radius:.4rem;color:#cffffa;background:#153331;cursor:pointer}button:disabled,textarea:disabled{opacity:.5;cursor:not-allowed}@media(max-width:650px){.chat{height:auto}.message{width:92%}form{grid-template-columns:1fr}button{width:100%}}
</style>
