<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchLogs, type RuntimeLogEntry } from '$lib/echo-client';
  export let apiBase:string; export let eventRevision=0;
  const eventTypes=['','signal.received','signal.routed','task.created','task.status_changed','action.created','action.executed','state.changed','runtime.started','runtime.stopped','error'];
  let severity='';let eventType='';let logs:RuntimeLogEntry[]=[];let loading=true;let error='';let mounted=false;let seen=-1;
  $: if(mounted&&eventRevision!==seen){seen=eventRevision;void load(false)}
  onMount(()=>{mounted=true;void load()});
  async function load(show=true){if(show)loading=true;try{logs=await fetchLogs(window.fetch.bind(window),apiBase,{severity,eventType,limit:250});error=''}catch{error='Structured runtime logs are unavailable.'}finally{loading=false}}
  function changeFilters(){void load()}
  const time=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleTimeString()};
  const pretty=(value:unknown)=>JSON.stringify(value,null,2);
</script>
<section class="logs" aria-labelledby="logs-heading"><header><div><p>Structured runtime logs</p><h2 id="logs-heading">Event record</h2></div><button onclick={()=>load()} disabled={loading} type="button">{loading?'Loading…':'Refresh'}</button></header>
  <div class="filters"><label><span>Severity</span><select bind:value={severity} onchange={changeFilters}><option value="">All severities</option><option value="info">Info</option><option value="warning">Warning</option><option value="error">Error</option></select></label><label><span>Event type</span><select bind:value={eventType} onchange={changeFilters}>{#each eventTypes as type}<option value={type}>{type||'All event types'}</option>{/each}</select></label><strong>{logs.length} events</strong></div>
  {#if error}<div class="error" role="status">{error}</div>{/if}
  {#if logs.length}<ol>{#each logs as log}<li class:error-row={log.severity==='error'}><div class="event"><time datetime={log.timestamp}>{time(log.timestamp)}</time><span class="severity">{log.severity}</span><strong>{log.event_type}</strong></div><div class="links">{#if log.entity_id}<code>entity {log.entity_id}</code>{/if}{#if log.signal_id}<code>signal {log.signal_id}</code>{/if}{#if log.task_id}<code>task {log.task_id}</code>{/if}{#if log.action_id}<code>action {log.action_id}</code>{/if}</div><pre>{pretty(log.metadata)}</pre></li>{/each}</ol>{:else if !loading}<p class="empty">No logs match these filters.</p>{/if}
</section>
<style>
  .logs{width:min(100%,86rem);margin:0 auto}header,.filters,.event,.links{display:flex;align-items:center;gap:1rem}header{justify-content:space-between;margin-bottom:1.4rem}h2,p{margin:0}h2{font-size:clamp(1.75rem,3vw,2.5rem)}header p,label span{color:#6f8093;font:.75rem ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase;margin-bottom:.4rem}button,select{border:1px solid #314153;border-radius:.4rem;color:#dce6ef;background:#14202c;padding:.6rem .85rem}button{cursor:pointer}.filters{flex-wrap:wrap;padding:1rem;border:1px solid #1d2a38;border-radius:.55rem .55rem 0 0;background:#0f1721}.filters label{display:grid}.filters strong{margin-left:auto;color:#778699;font-size:.8rem}ol{list-style:none;margin:0;padding:0;border:1px solid #1d2a38;border-top:0;border-radius:0 0 .55rem .55rem;overflow:hidden}li{display:grid;grid-template-columns:minmax(16rem,.55fr) minmax(12rem,.65fr) 1fr;gap:1rem;align-items:start;padding:.8rem 1rem;border-top:1px solid #1a2734;background:#0d141d}li:first-child{border-top:0}.event{align-items:baseline}.event time{color:#7b8999;font:.75rem ui-monospace,monospace}.event strong{font-size:.83rem}.severity{padding:.18rem .35rem;border:1px solid #294153;border-radius:.25rem;color:#77cfc9;font:.66rem ui-monospace,monospace;text-transform:uppercase}.error-row .severity{border-color:#61333b;color:#ef8992}.links{flex-wrap:wrap}.links code{color:#8190a2;font-size:.68rem}pre{overflow:auto;max-height:8rem;margin:0;color:#a4b2c2;font:.7rem/1.45 ui-monospace,monospace}.error,.empty{padding:1rem;border:1px solid #5d3038;color:#efb1b6;background:#251218}.empty{border-color:#1d2a38;color:#657487;background:#0d141d}@media(max-width:950px){li{grid-template-columns:1fr 1fr}pre{grid-column:1/-1}}@media(max-width:650px){li{grid-template-columns:1fr}.filters strong{width:100%;margin:0}}
</style>
